# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'napari_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(863, 70)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loadImageBtn = QtWidgets.QPushButton(Form)
        self.loadImageBtn.setObjectName("loadImageBtn")
        self.gridLayout_3.addWidget(self.loadImageBtn, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.numColorsCbox = QtWidgets.QComboBox(self.groupBox_5)
        self.numColorsCbox.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.numColorsCbox.setObjectName("numColorsCbox")
        self.numColorsCbox.addItem("")
        self.numColorsCbox.addItem("")
        self.numColorsCbox.addItem("")
        self.gridLayout_3.addWidget(self.groupBox_5, 0, 4, 2, 1)
        self.loadImageJroisBtn = QtWidgets.QPushButton(Form)
        self.loadImageJroisBtn.setObjectName("loadImageJroisBtn")
        self.gridLayout_3.addWidget(self.loadImageJroisBtn, 1, 0, 1, 1)
        self.saveImageJroisBtn = QtWidgets.QPushButton(Form)
        self.saveImageJroisBtn.setObjectName("saveImageJroisBtn")
        self.gridLayout_3.addWidget(self.saveImageJroisBtn, 1, 1, 1, 1)
        self.cropSelectedBtn = QtWidgets.QPushButton(Form)
        self.cropSelectedBtn.setObjectName("cropSelectedBtn")
        self.gridLayout_3.addWidget(self.cropSelectedBtn, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.frameEndBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.frameEndBox.setGeometry(QtCore.QRect(10, 20, 101, 22))
        self.frameEndBox.setMinimum(-1)
        self.frameEndBox.setMaximum(1000000)
        self.frameEndBox.setProperty("value", -1)
        self.frameEndBox.setObjectName("frameEndBox")
        self.defaultFramesBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.defaultFramesBtn.setGeometry(QtCore.QRect(120, 20, 51, 23))
        self.defaultFramesBtn.setObjectName("defaultFramesBtn")
        self.gridLayout_3.addWidget(self.groupBox_4, 0, 3, 2, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frameStartSbox = QtWidgets.QSpinBox(self.groupBox_3)
        self.frameStartSbox.setGeometry(QtCore.QRect(10, 20, 111, 22))
        self.frameStartSbox.setMaximum(100000)
        self.frameStartSbox.setObjectName("frameStartSbox")
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loadImageBtn.setText(_translate("Form", "Load image sequences"))
        self.groupBox_5.setTitle(_translate("Form", "Number of colors"))
        self.numColorsCbox.setCurrentText(_translate("Form", "2"))
        self.numColorsCbox.setItemText(0, _translate("Form", "1"))
        self.numColorsCbox.setItemText(1, _translate("Form", "2"))
        self.numColorsCbox.setItemText(2, _translate("Form", "3"))
        self.loadImageJroisBtn.setText(_translate("Form", "Load imageJ ROIs"))
        self.saveImageJroisBtn.setText(_translate("Form", "Save as imageJ ROIs"))
        self.cropSelectedBtn.setText(_translate("Form", "crop selected ROIs"))
        self.groupBox_4.setTitle(_translate("Form", "Frame end"))
        self.defaultFramesBtn.setText(_translate("Form", "default"))
        self.groupBox_3.setTitle(_translate("Form", "Frame start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
